# Generated by Django 5.0.7 on 2024-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
