# Generated by Django 5.0.7 on 2024-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_todoitems_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='name',
            field=models.CharField(default='elina', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitems',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
